### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by ViRb3**
FancyIndex doesn't encode special characters (e.g. square brackets) in URLs and many programs will fail to open such URLs. The fix is to encode the whole URL when copying file URL.

### CODE REVIEW

**Comment by ViRb3** [comment]
FancyIndex won't decode encoded square brackets, resulting in a 404. Any ideas how this could be solved?

**Comment by ViRb3** [comment]
Will be fixed in future FancyIndex build:
https://github.com/aperezdc/ngx-fancyindex/pull/97

**Comment by ViRb3** [comment]
After some extensive testing this workaround seems to allow copying working URLs including any special characters. Feel free to merge.

**Comment by fraoustin** [comment]
thank you

**Pull request merged**
